# Generated by Django 2.1.2 on 2019-12-02 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_professor_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, verbose_name='Matricula'),
            preserve_default=False,
        ),
    ]
